### ISSUE TITLE
Layer import : permit to choose default visibility of a new layer

### ISSUE THREAD

**Issue by kazemar** [kalisio/kano#207]
When I load a new layer, kano will try to show the items. But if the layer is big, my computer won't be able to show all the items, and won't give me the chance to set the properties (like visibility zoom range).

So it would be helpfull to give me the opportunity when loading the layer to directly set the default visibility option (default "on", but can be switched to "off").

**Comment by claustres** [comment]
The problem is that you cannot really know in advance if you need to hide the layer or not depending on your processing power. From the user point of view it is also not really convenient to load data without any feedback on the screen.

Actually, it would be a workaround to hide the layer when importing just because we know we can save it and it will be processed to generate tiles that can be properly displayed afterwards. We should probably directly provide the user with a feature to upload large datasets and warn him that it needs to be processed in the database before display.

I propose to open a dedicated issue, which is actually linked to https://github.com/kalisio/kdk/issues/80, this will be more explicit.
